
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1  
      MYSQL_DATABASE: ABC_USERS
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:

